version: '2'
services:
  db:
    build:
      context: ${WORKSPACE}/Dockerfiles
      dockerfile: PG-Dockerfile
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    restart: always
    container_name: mypostgres
    expose:
      - "5432"
  dbcli:
    build:
      context: ${WORKSPACE}/Dockerfiles
      dockerfile: PG-Dockerfile
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ${WORKSPACE}/data:/tmp/data
    links:
      - db:mypostgres
    container_name: dbcli
    entrypoint:
      - psql 
      - -h 
      - mypostgres 
      - -U 
      - postgres 
      - -f 
      - /tmp/data/pgdata.sql

