version: '2'
services:

  db:
    build:
      context: ${WORKSPACE}/Dockerfiles
      dockerfile: PG-Dockerfile
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    restart: always
    container_name: mypostgres

  dbcli:
    build:
      context: ${WORKSPACE}/Dockerfiles
      dockerfile: PG-Dockerfile
    environment:
      PGPASSWORD: ${PG_PASSWORD}
    volumes:
      - ${WORKSPACE}/data:/tmp/data
    container_name: dbcli
    depends_on: 
      - db
    restart: always
    entrypoint:
      - psql 
      - -h 
      - mypostgres 
      - -U 
      - postgres 
      - -f 
      - /tmp/data/pgdata.sql
